<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'app.football' shared service.

include_once $this->targetDirs[3].'/src/FootballBundle/Football/Football.php';
include_once $this->targetDirs[3].'/vendor/guzzlehttp/guzzle/src/ClientInterface.php';
include_once $this->targetDirs[3].'/vendor/guzzlehttp/guzzle/src/Client.php';

return $this->services['app.football'] = new \FootballBundle\Football\Football(${($_ = isset($this->services['csa_guzzle.client.football']) ? $this->services['csa_guzzle.client.football'] : $this->services['csa_guzzle.client.football'] = new \GuzzleHttp\Client(array('base_uri' => 'https://www.thesportsdb.com'))) && false ?: '_'}, ${($_ = isset($this->services['jms_serializer']) ? $this->services['jms_serializer'] : $this->load('getJmsSerializerService.php')) && false ?: '_'}, 1);
