<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'csa_guzzle.client.football' shared service.

include_once $this->targetDirs[3].'/vendor/guzzlehttp/guzzle/src/ClientInterface.php';
include_once $this->targetDirs[3].'/vendor/guzzlehttp/guzzle/src/Client.php';

return $this->services['csa_guzzle.client.football'] = new \GuzzleHttp\Client(array('base_uri' => 'https://www.thesportsdb.com'));
