<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXgwwqgg\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXgwwqgg/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXgwwqgg.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXgwwqgg\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXgwwqgg\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Xgwwqgg',
    'container.build_id' => '2636a262',
    'container.build_time' => 1538471569,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXgwwqgg');
